name: Feature Request
description: Suggest a new feature or enhancement for go-mermaid
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature, if possible please provide a PR with the implementation.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Clear description of the feature you'd like to see added
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: If you have ideas about how this could be implemented, share them here
      placeholder: This could be implemented by...
    validations:
      required: false
